---
title: "Daten zusammenspielen"
author: "Peter Baumgartner"
date: "2017-03-19"
output: 
        html_notebook:
                toc: yes
                toc_depth: 3
                
---
***

```{r label = "global-options", echo=FALSE, highlight=TRUE}
knitr::opts_chunk$set(
        message = F,
        error = F,
        warning = F,
        comment = NA,
        highlight = T,
        prompt = T
        )

if (!require("tidyverse")) 
        {install.packages("tidyverse", repos = 'http://cran.wu.ac.at/')
        library(tidyverse)}
if (!require("reshape2"))
        {install.packages("reshape2", repos = 'http://cran.wu.ac.at/')
        library(reshape2)}
if (!require("readxl"))
        {install.packages("readxl", repos = 'http://cran.wu.ac.at/')
        library(readxl)}
if (!require("pander"))
        {install.packages("pander", repos = 'http://cran.wu.ac.at/')
        library(pander)}

# install packages for writing Excel file (xlsx-format)
if (!require("xlsx")) 
        {install.packages("xlsx", repos = 'http://cran.wu.ac.at/')
        library(xlsx)}
if (!require("rJava"))
        {install.packages("rJava", repos = 'http://cran.wu.ac.at/')
        library(rJava)}
if (!require("xlsxjars"))
        {install.packages("xlsxjars", repos = 'http://cran.wu.ac.at/')
        library(xlsxjars)}


```

# Datensätze (Excelsheets) zusammenfügen

```{r combine-all-data-sets}


tirol1 <- readRDS("../daten/tirol.1.rds")
tirol2 <- readRDS("../daten/tirol.2.rds")
tirol3 <- readRDS("../daten/tirol.3.rds")
tirol4 <- readRDS("../daten/tirol.4.rds")
tirol5 <- readRDS("../daten/tirol.5.rds")
tirol0 <- do.call("cbind", list(tirol1, tirol2, tirol3, tirol4, tirol5))
tirol0 <- as_tibble(tirol0)
saveRDS(tirol0, file = "../daten/tirol0.rds")

write.xlsx(x = tirol0, file = "../daten/tirol0.xlsx", 
           sheetName = "Umfrage", col.names = TRUE, showNA = TRUE) 
       
```

# Kommentare beseitigen
```{r kommentare-beseitigen}
tirol <- select(tirol0, -starts_with("note."))
write.xlsx(x = tirol, file = "../daten/tirol.xlsx", 
           sheetName = "Umfrage", col.names = TRUE, showNA = TRUE) 
```

